import { provideIcons } from '@ng-icons/core';
import {
  heroArrowRightOnRectangle,
  heroBanknotes,
  heroBars3,
  heroBolt,
  heroCalendarDays,
  heroChartBar,
  heroCheckCircle,
  heroClipboardDocumentList,
  heroExclamationCircle,
  heroEye,
  heroHome,
  heroInbox,
  heroMoon,
  heroPencilSquare,
  heroPlus,
  heroRocketLaunch,
  heroSparkles,
  heroSun,
  heroTrash,
  heroTruck,
  heroUsers,
  heroXMark,
} from '@ng-icons/heroicons/outline';

/** App-wide icon registry. Add icons here as features are built. */
export const provideAppIcons = () =>
  provideIcons({
    heroArrowRightOnRectangle,
    heroBanknotes,
    heroBars3,
    heroBolt,
    heroCalendarDays,
    heroChartBar,
    heroCheckCircle,
    heroClipboardDocumentList,
    heroExclamationCircle,
    heroEye,
    heroHome,
    heroInbox,
    heroMoon,
    heroPencilSquare,
    heroPlus,
    heroRocketLaunch,
    heroSparkles,
    heroSun,
    heroTrash,
    heroTruck,
    heroUsers,
    heroXMark,
  });
