import { provideIcons } from '@ng-icons/core';
import {
  heroArrowLeft,
  heroArrowRightOnRectangle,
  heroBanknotes,
  heroBars3,
  heroBolt,
  heroCalendarDays,
  heroChartBar,
  heroCheckCircle,
  heroChevronDoubleLeft,
  heroChevronDoubleRight,
  heroChevronLeft,
  heroChevronRight,
  heroClipboardDocumentList,
  heroExclamationCircle,
  heroEye,
  heroHome,
  heroInbox,
  heroMagnifyingGlass,
  heroMoon,
  heroPencilSquare,
  heroPlus,
  heroRocketLaunch,
  heroSparkles,
  heroSun,
  heroTrash,
  heroTruck,
  heroUsers,
  heroXMark,
} from '@ng-icons/heroicons/outline';

/** App-wide icon registry. Add icons here as features are built. */
export const provideAppIcons = () =>
  provideIcons({
    heroArrowLeft,
    heroArrowRightOnRectangle,
    heroBanknotes,
    heroBars3,
    heroBolt,
    heroCalendarDays,
    heroChartBar,
    heroCheckCircle,
    heroChevronDoubleLeft,
    heroChevronDoubleRight,
    heroChevronLeft,
    heroChevronRight,
    heroClipboardDocumentList,
    heroExclamationCircle,
    heroEye,
    heroHome,
    heroInbox,
    heroMagnifyingGlass,
    heroMoon,
    heroPencilSquare,
    heroPlus,
    heroRocketLaunch,
    heroSparkles,
    heroSun,
    heroTrash,
    heroTruck,
    heroUsers,
    heroXMark,
  });
